SET @hour := -1;

SELECT (@hour := @hour + 1) AS HOUR,
(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @hour) AS COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23

-- 오답 
-- SELECT HOUR(DATETIME) AS HOUR,
-- COUNT(DATETIME) AS COUNT
-- FROM ANIMAL_OUTS
-- GROUP BY HOUR
-- ORDER BY HOUR